server:
  port: 8080

spring:
  application:
    name: his-api-gateway

  cloud:
    gateway:
      # Global CORS Configuration
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      # Circuit Breaker Configuration
      default-filters:
        - name: CircuitBreaker
          args:
            name: default-circuit-breaker
            fallbackUri: forward:/fallback/default
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 100
            redis-rate-limiter.burstCapacity: 200
            redis-rate-limiter.requestedTokens: 1

      # Service Discovery (Static for Docker)
      discovery:
        locator:
          enabled: false

      # HTTP Client Configuration
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s

      # Load Balancer Configuration
      loadbalancer:
        use404: true

  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          # JWT Configuration - can be disabled via profile
          enabled: false

  # Redis Configuration (for Rate Limiting)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      patient-service-cb:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s

      encounter-service-cb:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s

  # Retry Configuration
  retry:
    instances:
      patient-service:
        maxAttempts: 3
        waitDuration: 100ms
        exponentialBackoffMultiplier: 2
        enableExponentialBackoff: true

      encounter-service:
        maxAttempts: 3
        waitDuration: 100ms
        exponentialBackoffMultiplier: 2
        enableExponentialBackoff: true

# Health Check Configuration
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - gateway
          - circuitbreakers
          - circuitbreakerevents
          - prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      group:
        custom:
          include:
            - ping
            - diskSpace
            - circuitBreakers
    gateway:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.web.cors: DEBUG
    org.springframework.security: INFO
    de.his.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gateway-service.log
    max-size: 100MB
    max-history: 30

# Custom Configuration
his:
  gateway:
    # Security Configuration
    security:
      jwt:
        enabled: ${JWT_ENABLED:false} # Disable JWT by default
        secret: ${JWT_SECRET:default-secret-key-change-in-production}
        expiration: 86400 # 24 hours

      # RBAC Configuration (for future use)
      rbac:
        enabled: ${RBAC_ENABLED:false}
        admin-roles:
          - ADMIN
          - SYSTEM_ADMIN
        doctor-roles:
          - DOCTOR
          - PHYSICIAN
        nurse-roles:
          - NURSE
          - NURSE_PRACTITIONER
        readonly-roles:
          - READONLY
          - GUEST

    # Service Configuration
    services:
      patient:
        url: ${PATIENT_SERVICE_URL:http://patient-service:8081}
        timeout: 30s
        retries: 3
      encounter:
        url: ${ENCOUNTER_SERVICE_URL:http://encounter-service:8082}
        timeout: 30s
        retries: 3

    # Rate Limiting
    rate-limit:
      enabled: ${RATE_LIMIT_ENABLED:false}
      default-rate: 100 # requests per minute
      burst-capacity: 200

    # Audit Logging
    audit:
      enabled: true
      include-request-body: false
      include-response-body: false
      sensitive-headers:
        - authorization
        - x-api-key
        - cookie

# API Documentation
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Patient Service
        url: /docs/patient/api-docs
        display-name: "Patient Service API"
      - name: Encounter Service
        url: /docs/encounter/api-docs
        display-name: "Encounter Service API"
      - name: Gateway Service
        url: /api-docs
        display-name: "API Gateway"
