spring:
  application:
    name: his-authorization-service
  datasource:
    url: jdbc:postgresql://localhost:5432/his_db
    username: his_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: his_authorization
    show-sql: true
  liquibase:
    enabled: false

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
