spring:
  application:
    name: encounter-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/his_db
    username: his_user
    password: dev_password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: his_encounter
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-on-validation-error: false
    clean-disabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: his_encounter

  mvc:
    log-request-details: true

services:
  patient:
    url: http://patient-service:8081

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    de.his.encounter: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
