server:
  port: 8082

spring:
  application:
    name: encounter-service

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: his_encounter
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-on-validation-error: false
    clean-disabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/his_db
    username: his_user
    password: dev_password

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: his_encounter

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  liquibase:
    enabled: false

  security:
    user:
      name: admin
      password: dev-password
      roles: ADMIN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    de.his.encounter: DEBUG
    org.springframework.security: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

services:
  patient:
    url: http://patient-service:8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
