spring:
  application:
    name: patient-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/his_db
    username: his_user
    password: dev_password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: his_patient
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-on-validation-error: false # sicherer Standard
    clean-disabled: true # Clean komplett deaktivieren

  jpa:
    hibernate:
      ddl-auto: validate # Flyway verwaltet das Schema
    show-sql: false # SQL-Ausgabe über Logger unten
    properties:
      hibernate:
        format_sql: true
        default_schema: his_patient

  mvc:
    log-request-details: true # nur wirksam, wenn RequestLoggingFilter aktiv ist

# server.port NICHT setzen – Port kommt aus ENV (SERVER_PORT=8081)

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    de.his.patient: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
