server:
  port: 8081

spring:
  application:
    name: patient-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/his_patient}
    username: ${SPRING_DATASOURCE_USERNAME:his_user}
    password: ${SPRING_DATASOURCE_PASSWORD:dev_password}

  jpa:
    hibernate:
      ddl-auto: update # create-drop → update (weniger aggressiv)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: never # Schema-Initialisierung deaktivieren

  liquibase:
    enabled: false

  security:
    user:
      name: admin
      password: dev-password
      roles: ADMIN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    de.his.patient: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG # SQL-Debugging aktivieren
    org.hibernate.type: TRACE # Parameter-Debugging
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/patient-service.log
    max-size: 100MB
    max-history: 30

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
