server:
  port: 8080

spring:
  application:
    name: patient-service

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: pvs_patient
    baseline-on-migrate: true
    validate-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/his_db
    username: his_user
    password: dev_password

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  liquibase:
    enabled: false # Liquibase deaktivieren für lokale H2

  security:
    user:
      name: admin
      password: dev-password
      roles: ADMIN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    de.his.patient: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
