spring:
  application:
    name: patient-service

  # PostgreSQL Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/his_db
    username: his_user
    password: dev_password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: his_patient
    baseline-on-migrate: true
    validate-on-migrate: true

  # JPA/Hibernate for PostgreSQL
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: his_patient

  # Disable H2 Console
  h2:
    console:
      enabled: false

  # Security
  security:
    user:
      name: admin
      password: dev-password
      roles: ADMIN

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    de.his.patient: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO
